version: '3.3'

services:

  db:
    image: postgres:14.7
    container_name: db
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  main_api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: main_api
    volumes:
      - static_volume:/referal/static
      - db:/referal/db
    command: >
          sh -c "python manage.py collectstatic --noinput &&
                 python manage.py migrate &&
                 gunicorn --bind 0.0.0.0:8000 config.wsgi"
    env_file:
      - .env
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    hostname: redis
    expose:
      - 6379

  celery:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c 'celery -A config worker -l info'
    volumes:
      - .:/referal
    links:
      - redis
    depends_on:
      - redis
      - main_api

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./deployment/nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - etc-letsencrypt:/etc/letcsencrypt
      - static_volume:/enactus/static
    depends_on:
      - main_api
    expose:
      - 80
    ports:
      - "80:80"
      - "443:443"
    restart: always

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email maursualex@gmail.com -d simplereferal.com --agree-tos

volumes:
  static_volume:
  media_volume:
  db:
  etc-letsencrypt:
