# Generated by Django 4.2.4 on 2023-08-07 14:57
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="Phone number"
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        help_text='Code that other users can write to "refered_by" field',
                        unique=True,
                        verbose_name="Invite_code",
                    ),
                ),
                (
                    "login_code",
                    models.CharField(
                        blank=True,
                        help_text="Code that app send on phone number of user",
                        verbose_name="Login code",
                    ),
                ),
                (
                    "refered_by",
                    models.CharField(
                        blank=True,
                        help_text="Invite code of other user",
                        verbose_name="Refered by",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Defines permission to login to admin site",
                        verbose_name="Is staff",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Is user can login to admin site with all permissions",
                        verbose_name="Is superuser",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["id", "phone_number"], name="referal_use_id_fb8968_idx"
                    )
                ],
            },
        ),
    ]
