# Generated by Django 4.2.4 on 2023-08-08 15:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("referal", "0002_alter_user_login_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(unique=True, verbose_name="Phone number"),
        ),
    ]
