# Generated by Django 4.2.4 on 2023-08-08 15:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("referal", "0004_alter_user_login_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_code",
            field=models.CharField(
                blank=True,
                help_text="Code that app send on phone number of user",
                unique=True,
                verbose_name="Login code",
            ),
        ),
    ]
